name: ubuntu builds
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
       sudo apt install busybox -y
       wget https://github.com/fatedier/frp/releases/download/v0.48.0/frp_0.48.0_linux_amd64.tar.gz
       tar zxvf frp_0.48.0_linux_amd64.tar.gz && mv frp_0.48.0_linux_amd64/* .
       rm frpc.ini
       wget https://raw.githubusercontent.com/neoterm-extra/action-ssh/main/frpc.ini
       git clone https://github.com/AkiraNoSushi/kernel_cherry_sdm439 -b ksu kernel
       git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc
       git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc-arm
       cd kernel
       export ARCH=arm64
       export SUBARCH=arm64
       export KBUILD_BUILD_HOST=mcstark
       export KBUILD_BUILD_USER=cute
       export LOCALVERSION=-mcstark
       export PATH="../gcc/bin:../gcc-arm/bin:$PATH"
       mkdir out
       args="-j$(nproc --all) \
       ARCH=arm64 \
       SUBARCH=arm64 \
       O=out \
       CROSS_COMPILE=aarch64-linux-gnu- \
       CROSS_COMPILE_ARM32=arm-linux-androideabi- \
       CLANG_TRIPLE=aarch64-linux-android- "
       make ${args} mrproper
       make ${args} cherry-mi439_defconfig
       make ${args} 
       ls -lh  out/arch/arm64/boot
       busybox httpd -p 8099
       ../frpc -c ../frpc.ini
