on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '127.0.0.1'
        port: 22
        username: 'root'
        password: 'password'
        localPath: './dist/index.js'
        remotePath: './'
