name: ubuntu builds
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
       sudo apt install busybox openssh-server python3-pip python-is-python3 -y
       wget https://github.com/fatedier/frp/releases/download/v0.48.0/frp_0.48.0_linux_amd64.tar.gz
       tar zxvf frp_0.48.0_linux_amd64.tar.gz && mv frp_0.48.0_linux_amd64/* .
       sudo chmod 777 patch-sshd.sh 
       sudo bash patch-sshd.sh
       sudo systemctl start sshd 
       sudo systemctl restart sshd
       sudo systemctl start ssh
       sudo systemctl restart ssh
       pip3 install wssh webssh
       cp -rf wssh ~/.local/bin
       cp -rf wsshd ~/.local/bin
       nohup wssh --address='127.0.0.1' --port=8888 &
       #
       ./frpc -c frpc.ini
