name: build clover   docker kernel
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: buildkernel
       run: ./clover.sh

     - name: Start SSH Server
       if: ${{ failure() }}
       env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
         SSH_PASSWORD: ${{ secrets.USER_PASS }}
       run: |
          chmod +x ./ssh-server.sh &&  ./ssh-server.sh

     - name: Sleepd
       if: ${{ failure() }}
       run: sleep 3h
