name: ubuntu builds
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
       sudo apt install busybox -y
       wget https://github.com/fatedier/frp/releases/download/v0.48.0/frp_0.48.0_linux_amd64.tar.gz
       tar zxvf frp_0.48.0_linux_amd64.tar.gz
       rm frpc.ini
       wget https://raw.githubusercontent.com/neoterm-extra/action-ssh/main/frpc.ini
       git clone https://github.com/AkiraNoSushi/kernel_cherry_sdm439 kernel
       git clone https://github.com/kdrag0n/proton-clang.git /root/proton-clang --depth=1
       cd kernel && curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
       export ARCH=arm64
       export SUBARCH=arm64
       export KBUILD_BUILD_HOST=mcstark
       export KBUILD_BUILD_USER=cute
       export LOCALVERSION=-mcstark
       export PATH="../proton-clang/bin:$PATH"
       mkdir out
       args="-j$(nproc --all) \
       ARCH=arm64 \
       SUBARCH=arm64 \
       O=out \
       CC=clang \
       CROSS_COMPILE=aarch64-linux-gnu- \
       CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
       CLANG_TRIPLE=aarch64-linux-gnu- \
       AR=llvm-ar \
       NM=llvm-nm \
       OBJCOPY=llvm-objcopy \
       OBJDUMP=llvm-objdump \
       STRIP=llvm-strip "
       make ${args} mrproper
       make ${args} cherry-mi439_defconfig
       make ${args} 
       ls -lh  out/arch/arm64/boot
       busybox httpd -p 8099
       ./frpc -c frpc.ini
